stages:
  train:
    cmd : dvc run -n train \
      -d train.py \
      -d wine_quality.csv \
      -o metrics.txt \
      -o residuals.png \
      python train.py
    deps:
      
      - wine_quality.csv

  